import BottomNavBar from "@/components/Navbar/BottomNavBar"

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
      <>
        {children}
      <BottomNavBar/>
      </>
  )
}
