import { Inter } from 'next/font/google'
import '../styles/globals.css'
import { InvestorPanelProvider } from '@/context/context'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <InvestorPanelProvider>
      <body className={inter.className}>{children}</body>
      </InvestorPanelProvider>
    </html>
  )
}
